Vagrant.configure("2") do |config|

    config.vm.box = "alvaro/bionic64"

    config.vm.hostname = "TFE-demo"
    config.vm.network "private_network", ip: "192.168.56.33"
     
    config.vm.provider "virtualbox" do |v|
        v.memory = 4096
        v.cpus = 2
      end

  end