#!/usr/bin/env bash

sudo apt-get install -y jq

# download the certificate generated by TFE and add it to the server so it is trusted
echo -n | openssl s_client -connect 192.168.56.33.nip.io:8800 | openssl x509 > tfe_certificate.crt
cp tfe_certificate.crt /usr/local/share/ca-certificates/
update-ca-certificates

# We have to wait for TFE be fully functioning before we can continue
while true; do
    if curl -I "https://192.168.56.33.nip.io/admin" 2>&1 | grep -w "200\|301" ; 
    then
        echo "TFE is up and running"
        echo "Will continue in 1 minutes with the final steps"
        sleep 60
        break
    else
        echo "TFE is not available yet. Please wait..."
        sleep 60
    fi
done

pushd /vagrant/config

# Make sure you can upgrade right away and disable server version pinning
replicatedctl params set ReleaseSequence --value 0

initial_token=$(/usr/local/bin/replicated admin --tty=0 retrieve-iact | tr -d '\r')

export TOKEN=`curl --header "Content-Type: application/json" --request POST --data @create_tfe_user.json https://192.168.56.33.nip.io/admin/initial-admin-user?token=${initial_token} | jq '.token' | tr -d '"'`

echo ""
echo "#######################################################"
echo "#              TFE installation complete              #"
echo "# TFE dashboard: https://192.168.56.33.nip.io:8800    #"
echo "# TFE Application: https://192.168.56.33.nip.io       #" 
echo "#######################################################"


echo $TOKEN

curl \
  --header "Authorization: Bearer $TOKEN" \
  --header "Content-Type: application/vnd.api+json" \
  --request POST \
  --data '{"data": { "type": "organizations", "attributes": {"name": "test2", "email": "patrick.munne@hashicorp.com"}}}' \
  https://192.168.56.33.nip.io/api/v2/organizations

curl \
  --header "Authorization: Bearer $TOKEN" \
  --header "Content-Type: application/vnd.api+json" \
  --request PATCH \
  --data '{"data": {"id": "smtp", "type": "smtp-settings", "attributes": {"enabled": true,"host": "smtp.mailtrap.io", "port": 587, "username": "e44a7dd19bc06f", "password": "4e993aca5d63ff", "sender": "pietje@klaasje.nl", "test-email-address": "pietje@klaasje.nl", "auth": "login"}}}' \
  https://192.168.56.33.nip.io/api/v2/admin/smtp-settings
